### ISSUE TITLE
Disabled menus are not completely disabled

### ISSUE THREAD

**Issue by kmccurley** [IACR/program-editor#157]
adding the class "disabled" to a bootshit dropdown menu doesn't actually disable a click event on the menu - it just puts up a pretty icon over it. If you click on a menu, it shows "false". Apparently we need to modify the handlers to check for the disabled class on the menu item and act accordingly to simply return true. The obeyMenu parameter is not enough.

**Comment by kaymckelly** [comment]
Note to self: see top answer, js bit.
