### ISSUE TITLE
Provide an extra field below title

### ISSUE THREAD

**Issue by kmccurley** [IACR/program-editor#159]
The search feature to import DOIs on crypto 2019 retried only 7/8 of the DOIs. This is an unacceptable failure rate and we should investigate what is causing it.

**Comment by kmccurley** [comment]
Note that I was also seeing console errors on chrome on windows 10.:

![image](https://user-images.githubusercontent.com/14105363/62810555-170ab200-bab3-11e9-8633-a663837dfdd5.png)

**Comment by kmccurley** [comment]
This should be split in two pieces, because one is a lookup problem and one is a CORS problem. On the lookup problem I discovered that the problem is editors are changing the title of the article to include things like: "Joint presentation with next talk:" at the beginning of the title, which makes it impossible to look up the paper by the original title. I suggest that we should provide more explicit support for joint presentation of two papers in a single slot. The solution I propose is to have an optional "subtitle" or "note" on a talk to indicate alternative information that is shown in the program. That "subtitle" or "note" could include things like:

- Joint presentation with the next paper
- presented by <insert name>
- best paper award
- invited talk
- presented by videoconference
- Panel discussion
- Award presentation

Then in the editor we should warn people not to change the title so that lookup of DOI will succeed.

**Comment by kmccurley** [comment]
I'm leaving this as a single issue, but at least the CORS issue is fixed. In addition, the crossref.org API has changed and no longer supports using query.title. I plan to switch to using query.bibliographic as [advised here](https://status.crossref.org/incidents/4y45gj63jsp4?u=zs4ylq20k10f). Even after making this change, I'm still seeing one more issue: the progress bar never gets to 100% on the TCC program.
![image](https://user-images.githubusercontent.com/14105363/67051251-73abce00-f0ef-11e9-8314-d56248de23e3.png)

**Comment by kmccurley** [comment]
This one just keeps uncovered more and more errors. It turns out that the crossref api has its own bug that occurs if the word "AND" in all caps appears in the title of a paper, and sure enough we have one of these in the [TCC 2019 list of accepted papers](https://tcc.iacr.org/2019/acceptedpapers.html). I filed an [issue on this](https://gitlab.com/crossref/issues/issues/502) but it causes a 500 error on the lookup for this one.

**Comment by kmccurley** [comment]
The plan to fix this is to 

1. add a field to the JSON schema for talk to have an optional field called "note". We thought about subtitle but that would conflict with usage in bibliographic databases like crossref.
2. add the note field in the modal to edit a talk
3. when the modal is populated, make sure to populate this field.
4. when the talk is saved, update the relevant field. If note is empty, don't bother to add it.

There would be a second pull request for the program template to display this.

**Comment by kaymckelly** [comment]
Resolved with #239
