### ISSUE TITLE
Import DOIs from crossref

### ISSUE THREAD

**Issue by kaymckelly** [IACR/program-editor#175]
Couple of things with this.

1. The status bar is comically tiny in the modal for this.
2. When results are found, it looks as though they should display below the search/cancel buttons on the modal, but do not appear when search is finished.

This is related to issue #171 but I suspect the extra space at the bottom of this modal can at least be fixed, whether the results appear or not.

**Comment by kmccurley** [comment]
It's not clear how to handle the case where it finds 72/75 DOIs. The three remaining ones probably failed because the title didn't exactly match the paper, and they have to be edited individually. They can be found in the program because they lack the paper icon. I'm not sure how to improve this.

**Comment by kaymckelly** [comment]
Looks better, ignore part 2
