### ISSUE TITLE
font sizes need to be adjusted everywhere.

### ISSUE THREAD

**Issue by kmccurley** [IACR/program-editor#178]
It seems that this is barely usable on my laptop under both firefox and chrome.

**Comment by kmccurley** [comment]
Note that the talk modal doesn't even show on my screen. 
![talkmodal](https://user-images.githubusercontent.com/14105363/66614969-c7faff00-eb7f-11e9-84da-386a93cf402c.png)

**Comment by kaymckelly** [comment]
We're now both satisfied with the font sizes.
